#!/usr/bin/env bash
#configuring Nginx so that its HTTP response contains a custom header

sudo apt-get -y update                                            
sudo apt-get -y install nginx    
sudo service nginx restart
sudo ufw allow 'Nginx HTTP'  
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/save_default
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
