#!/usr/bin/env bash
# Configures a new HAproxy as a load balancer

# Update package lists
apt-get -y update

# Install HAproxy (optional: specify version if necessary)
apt-get -y install haproxy

# Configure haproxy to distribute requests using a roundrobin algorithm
cat <<EOF >> /etc/haproxy/haproxy.cfg
frontend sammykingx.tech
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 64820-web-01 100.26.152.157:80 check
    server 64820-web-02 52.86.102.6:80 check
EOF

# Restart HAproxy service
systemctl restart haproxy
