#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
cat >>/etc/haproxy/haproxy.cfg <<EOL

frontend firstbalance
        bind *:80
        option forwardfor
        default_backend webservers

backend webservers
        balance roundrobin
        server webserver1 34.73.190.173:80
        server webserver2 18.208.189.15:80
        option httpchk

EOL
sudo service haproxy restart
