#!/usr/bin/env bash
#
# To infinity and beyond...
# Write PID to pidfile (default '/var/run/holbertonscript.pid')
# Remove pidfile and exit upon receiving SIGTERM or SIGQUIT

sleep() {
  ! read -rt "$1"
} <> <(:)

echo "$$" >| "${pidfile:=/var/run/holbertonscript.pid}"

trap '
  echo "Y U no love me?!"
' INT
trap '
  rm -f "${pidfile}" 2>/dev/null
  exit 131
' QUIT
trap '
  echo "I hate the kill command"
  rm -f "${pidfile}" 2>/dev/null
  exit 143
' TERM

while true
do
  echo 'To infinity and beyond'
  sleep 2
done
