#!/usr/bin/env bash
# The script.
pid=$(pgrep -f 100-process_and_pid_file)
echo "$pid" > holbertonscript.pid
sudo mv ./holbertonscript.pid /var/run/
while ((1)); do
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command" && sudo rm "/var/run/holbertonscript.pid" && kill -SIGKILL $pid' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
done
